language: java
jdk:
  - oraclejdk7
  - openjdk6
  - oraclejdk8
env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring4
    - PROFILE=spring32-next
    - PROFILE=spring4-next
    - PROFILE=querydsl-next
    - PROFILE=hibernate-41
    - PROFILE=hibernate-42
    - PROFILE=hibernate-43
cache:
  directories:
    - $HOME/.m2
install: true
script: "mvn clean dependency:list test -P${PROFILE} -Dsort"