language: java

jobs:
  allow_failures:
    - env: PROFILE=hibernate-next

cache:
  directories:
    - $HOME/.m2

install: true

script: "./mvnw -Pjava11 clean dependency:list test -Pjava11,${PROFILE} -Dsort -B"
