language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring41-next
    - PROFILE=spring42-next
    - PROFILE=hibernate-41
    - PROFILE=hibernate-42
    - PROFILE=hibernate-43
    - PROFILE=hibernate-5
    - PROFILE=querydsl-next

sudo: false

cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
