---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: spring-data-jpa-github

outputs:
- name: spring-data-jpa-artifactory

caches:
- path: maven

run:
  path: spring-data-jpa-github/ci/build.sh
